### PR TITLE
script modified to work with current gentoo mirrors and directory layout, logic simplified

### PR DESCRIPTION
**Pull request by kt97679**
I verified that this works ok on the oracle cloud vm running ubuntu 20.04. It was successfully converted into gentoo.

### CODE REVIEW

**Comment by oglueck** [comment]
first commit merged, but i am not sure about 2nd commit. It looks like you are no longer chrooting into the image and instead you rely on original OS be able to do all that (emerge-webrsync). This can't possibly work on non-gentoo.

**Comment by kt97679** [comment]
I'm sorry, I'm not relying on the original os. Chroot is not needed since I'm running emerge-webrsync after I moved gentoo files into root. So we essentially already have gentoo running as our main os. I mentioned in the description that I successfully converted ubuntu 20.04 into gentoo using this script. Please let me know if something is still unclear, I can provide more details.

**Comment by oglueck** [comment]
Understood and restructured the code. Thanks for your contribution.

**Comment by kt97679** [comment]
Thank you! Please note that you left line https://github.com/oglueck/to-gentoo/blob/master/to-gentoo#L164 without change. In my case I had to modify it: https://github.com/kt97679/to-gentoo/blob/master/to-gentoo#L131 because on ubuntu some root directories are symlinks. If target is moved before symlink itself [ -e $dir ] will fail and symlink will not be moved to /orig. After that mv from the /gentoo will fail as well.

Another minor note: mount and umount are no longer requirements https://raw.githubusercontent.com/kt97679/to-gentoo/master/to-gentoo

**Comment by oglueck** [comment]
Now I understand why you did that. Fixed by moving the symlinks correctly.

mount is still used for mounting /dev/shm, but umount is gone.

**Comment by kt97679** [comment]
Thank you very much for the changes! I'm not sure about other distributions but at least on the ubuntu 20.04 there was no need to remount /dev/shm. What distributions you saw that had /dev/shm as a symlink?

Another minor note: you don't need to install netifrc and dhcpd in this line https://github.com/oglueck/to-gentoo/blob/master/to-gentoo#L179 netifrc is now part of the stage3 and if dhcpd is not installed udhcpc from the busybox will be used and it works really well.

**Pull request closed without merging**
